# Maps availability zones in source cloud to zones in destination
#
# Required in cases when availability zones from source cloud are not available
# in destination cloud.
#
# Format:
#
#  <source-availability-zone-name1>: <destination-availability-zone-name1>
#  <source-availability-zone-name2>: <destination-availability-zone-name2>
#  $$default: <default-availability-zone>
#
# Default availability zone is used for cases when there are no rules
# defined for availability zone.

$$default: nova
